package hr.eestec_zg.cvdbbackend.domain.model;

public enum StudyProgramme {
    COMPUTING,
    TELECOMMUNICATIONS,
    SOFTWARE_ENGINEERING,
    COMPUTING_SCIENCE,
    COMPUTER_ENGINEERING,
    INFORMATION_PROCESSING,
    ELECTROTECHNIC,
    AUTOMATIZATION,
    ELECTRONIC_AND_COMPUTER_ENGINEERING,
    ELECTRONICS,
    ELECTRICAL_POWER_ENGINEERING,
    WIRELESS_SYSTEMS
}
